// Garante que as variáveis de ambiente são carregadas

// Configurações da API Asaas
export const ASAAS_CONFIG = {
  SANDBOX_URL: "https://api-sandbox.asaas.com/v3",
  PRODUCTION_URL: "https://api.asaas.com/v3",
  get BASE_URL() {
    return process.env.ASAAS_SANDBOX == "true"
      ? this.PRODUCTION_URL
      : this.SANDBOX_URL;
  },

  API_KEY:
    process.env.ASAAS_SANDBOX == "true"
      ? "$aact_prod_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OmJhMzFmMjFkLTMzODctNDhkOC05N2E4LTJmZTJkNGQ4NTZhMjo6JGFhY2hfNzI3MWRkMGItODU3NS00Njk3LThjOTQtODRhMjY4ZWQ0ZDE3"
      : "$aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OmZiMjRhNjQyLTRmMGUtNDc4Ny04MjAzLTY3NzViMWUzYWRjNzo6JGFhY2hfYjg5YzgyZmItMzAzNS00MzJlLWExYTItNmQ1OTZmMTE4NTM3",
};

// Headers padrão para requisições
export const ASAAS_HEADERS = {
  "Content-Type": "application/json",
  Authorization: `Bearer ${ASAAS_CONFIG.API_KEY}`,
};

// Tipos de cobrança disponíveis
export const BILLING_TYPES = {
  BOLETO: "BOLETO",
  PIX: "PIX",
  CREDIT_CARD: "CREDIT_CARD",
  UNDEFINED: "UNDEFINED",
} as const;

// Ciclos de assinatura
export const SUBSCRIPTION_CYCLES = {
  WEEKLY: "WEEKLY",
  BIWEEKLY: "BIWEEKLY",
  MONTHLY: "MONTHLY",
  BIMONTHLY: "BIMONTHLY",
  QUARTERLY: "QUARTERLY",
  SEMIANNUALLY: "SEMIANNUALLY",
  YEARLY: "YEARLY",
} as const;

// Status de pagamentos
export const PAYMENT_STATUS = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  RECEIVED: "RECEIVED",
  OVERDUE: "OVERDUE",
  REFUNDED: "REFUNDED",
  RECEIVED_IN_CASH: "RECEIVED_IN_CASH",
  REFUND_REQUESTED: "REFUND_REQUESTED",
  REFUND_IN_PROGRESS: "REFUND_IN_PROGRESS",
  CHARGEBACK_REQUESTED: "CHARGEBACK_REQUESTED",
  CHARGEBACK_DISPUTE: "CHARGEBACK_DISPUTE",
  AWAITING_CHARGEBACK_REVERSAL: "AWAITING_CHARGEBACK_REVERSAL",
} as const;

// Status de assinaturas
export const SUBSCRIPTION_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  OVERDUE: "OVERDUE",
  EXPIRED: "EXPIRED",
} as const;

// Eventos de webhook
export const WEBHOOK_EVENTS = {
  PAYMENT_CREATED: "PAYMENT_CREATED",
  PAYMENT_UPDATED: "PAYMENT_UPDATED",
  PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
  PAYMENT_OVERDUE: "PAYMENT_OVERDUE",
  PAYMENT_DELETED: "PAYMENT_DELETED",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  PAYMENT_RESTORED: "PAYMENT_RESTORED",
  SUBSCRIPTION_CREATED: "SUBSCRIPTION_CREATED",
  SUBSCRIPTION_UPDATED: "SUBSCRIPTION_UPDATED",
  SUBSCRIPTION_DELETED: "SUBSCRIPTION_DELETED",
} as const;
